FROM node:16 as build

WORKDIR /client

COPY package*.json ./
RUN yarn install

COPY . ./

RUN yarn build


FROM ubuntu:18.04
RUN apt update -y \
    && apt install nginx curl vim -y \
    && apt-get install software-properties-common -y \
    && apt-get clean


EXPOSE 80
STOPSIGNAL SIGTERM

COPY --from=build /client/out /var/www/html

CMD ["nginx", "-g", "daemon off;"]